mysite/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.new_book, name='new_book'),
    path('<int:id>/', views.book_update, name='book_update'),
    path('delete/<int:id>/', views.book_delete, name='book_delete'),
    path('list/', views.book_list, name='book_list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include("books.urls")),
]

mysite/books/models.py
from django.db import models
from isbn_field import ISBNField


class Book(models.Model):
    author = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    date = models.PositiveIntegerField()
    publisher = models.CharField(max_length=100)
    isbn = ISBNField(unique=True)

    def __str__(self):
        return self.title

mysite/books/forms.py
from .models import Book
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'date', 'publisher', 'isbn']
        labels = {
            'title': _('Введите название книги'),
            'author': _('Введите автора'),
            'date': _('Введите год'),
            'publisher': _('Введите издание'),
            'isbn': _('Введите isbn'),
        }
        error_massages = {'title': {'required': _('Заполните название')}}

mysite/books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book
from .forms import BookForm


def new_book(request):
    # Create
    title = 'Добавить книгу'
    button = 'Добавить'
    form = BookForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        data = form.save(commit=False)
        data.save()
        return redirect('books:book_list')
    return render(request, 'new_book.html', {'form': form, 'title': title, 'button': button})


def book_list(request):
    # Read
    books = Book.objects.all()
    return render(request, 'book_list.html', {'books': books})


def book_update(request, id):
    # Update
    title = 'Редактировать запись c ISBN'
    button = 'Редактировать'
    book = get_object_or_404(Book, id=id)
    form = BookForm(
        request.POST or None, files=request.FILES or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books:book_list')
    return render(
        request, 'new_book.html',
        {'form': form, 'title': title, 'button': button, 'book': book},
    )


def book_delete(request, id):
    # delete
    book = get_object_or_404(Book, id=id)
    book.delete()
    return redirect('books:book_list')

mysite/books/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="col-md-10 offset-md-1 mt-5">
            <div class="jumbotron">
              <h1 class="display-4">Добавление новой книги</h1>
              <p class="lead">Простое добавление книг в реестр</p>
              <hr class="my-4">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
</body>
</html>

mysite/books/templates/book_list.html
{% extends "base.html" %}
{% block title %}Список книг{% endblock %}
{% block content %}
<p>Здесь будет список для просмотра и редактирования книг</p>
    <table class="table table-borderless">
        <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Автор</td>
            <td>Название</td>
            <td>Издательство</td>
            <td>Год</td>
            <td>ISBN</td>
            <td><a href="{% url 'books:new_book' %}" class="btn btn-primary">Добавить книгу</a></td>
        </tr>
        </thead>
        <tbody>
        <tr>
        {% for book in books %}
            <td>{{book.author}}</td>
            <td>{{book.title}}</td>
            <td>{{book.publisher}}</td>
            <td>{{book.date}}</td>
            <td>{{book.isbn}}</td>
            <td>
                <a href="{% url 'books:book_update' book.id %}" class="btn btn-primary">Редактировать</a>
                <form action="{% url 'books:book_delete' book.id%}" method="post" class="d-inline">
                    {%csrf_token%}
                     <button type="submit" class="btn btn-success"> Удалить книгу</button>
                </form>
            </td>
        </tr>
        {%endfor%}
        </tbody>
    </table>

{% endblock content %}

mysite/books/templates/new_book.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{title}}{{book.isbn}}{% endblock %}

{% block content %}
<p>{{title}}{{book.isbn}}</p>

<form action="" method="post" autocomplete="off">
    {%csrf_token%}
    {{form|crispy}}
    <button type="submit" class="btn btn-success"> {{button}}</button>
    <a href="{% url 'books:book_list'%}" class="btn btn-primary">Перейти к списку книг</a>
</form>

{% endblock content %}